
import type { Product, Category, Order, MockAdminClient } from '@/lib/types';

export const mockCategories: Category[] = [
  { id: 'corporate-sets', name: 'Корпоративные наборы', slug: 'corporate-sets', description: 'Эксклюзивные наборы для корпоративных клиентов.' },
  { id: 'wedding-favors', name: 'Свадебные комплименты', slug: 'wedding-favors', description: 'Изящные комплименты для гостей на свадьбу.' },
  { id: 'scented-candles', name: 'Аромасвечи', slug: 'scented-candles', description: 'Ароматические свечи ручной работы с уникальными запахами.' },
  { id: 'tasty-home', name: 'Вкусный дом', slug: 'tasty-home', description: 'Товары для создания уюта и приятной атмосферы в доме.' },
  { id: 'gypsum-paradise', name: 'Гипсовый рай', slug: 'gypsum-paradise', description: 'Элегантные изделия из гипса для декора.' },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    sku: 'ASKM-LAV-001',
    name: {
      en: 'Lavender Bliss Candle',
      ru: 'Свеча "Лавандовое Блаженство"',
      uz: 'Lavanda Rohari Shami',
    },
    description: {
      en: 'Soothing lavender scented candle, perfect for relaxation. Made with natural soy wax.',
      ru: 'Успокаивающая свеча с ароматом лаванды, идеально подходит для релаксации. Изготовлена из натурального соевого воска.',
      uz: 'Tinchlantiruvchi lavanda hidli sham, dam olish uchun mukammal. Tabiiy soya mumidan tayyorlangan.',
    },
    price: 229900,
    costPrice: 150000,
    category: 'Аромасвечи', 
    images: ['https://placehold.co/600x400.png?text=Lavender+Candle+1', 'https://placehold.co/600x400.png?text=Lavender+Candle+2', 'https://placehold.co/600x400.png?text=Lavender+Candle+3'],
    mainImage: 'https://placehold.co/600x400.png?text=Lavender+Candle+1',
    scent: 'Лаванда',
    material: 'Соевый воск',
    dimensions: '8см x 10см',
    burningTime: 'Примерно 45 часов',
    stock: 15,
    attributes: [{key: 'Цвет', value: 'Фиолетовый'}],
    isActive: true,
  },
  {
    id: '2',
    sku: 'ASKM-VAN-002',
    name: {
      en: 'Vanilla Dream Candle',
      ru: 'Свеча "Ванильная Мечта"',
      uz: 'Vanil Orzusi Shami',
    },
    description: {
      en: 'A warm and inviting vanilla bean fragrance that fills your home with comfort.',
      ru: 'Теплый и манящий аромат ванильных бобов, наполняющий ваш дом уютом.',
      uz: 'Uyingizni shinamlik bilan to\'ldiradigan iliq va jozibali vanil donalari ifori.',
    },
    price: 245000,
    costPrice: 160000,
    category: 'Аромасвечи', 
    images: ['https://placehold.co/600x400.png?text=Vanilla+Candle+1', 'https://placehold.co/600x400.png?text=Vanilla+Candle+2'],
    mainImage: 'https://placehold.co/600x400.png?text=Vanilla+Candle+1',
    scent: 'Ваниль',
    material: 'Пчелиный воск (смесь)',
    dimensions: '9см x 12см',
    burningTime: 'Примерно 60 часов',
    stock: 20,
    attributes: [{key: 'Цвет', value: 'Кремовый'}],
    isActive: true,
  },
  {
    id: '3',
    sku: 'ASKM-SWA-003',
    name: {
      en: 'Elegant Swan Gypsum Figure',
      ru: 'Элегантная гипсовая фигурка "Лебедь"',
      uz: 'Nafis gipsli "Oqqush" haykalchasi',
    },
    description: {
      en: 'A beautifully detailed gypsum figure of a swan, perfect as a centerpiece.',
      ru: 'Красиво детализированная гипсовая фигурка лебедя, идеально подходящая в качестве центрального элемента декора.',
      uz: 'Markaziy element sifatida juda mos keladigan, chiroyli tarzda ishlangan oqqush gips haykalchasi.',
    },
    price: 350000,
    costPrice: 230000,
    category: 'Гипсовый рай', 
    images: ['https://placehold.co/600x400.png?text=Swan+Figure'],
    mainImage: 'https://placehold.co/600x400.png?text=Swan+Figure',
    scent: 'Без запаха',
    material: 'Гипс',
    dimensions: '15см x 12см x 10см',
    stock: 8,
    attributes: [{key: 'Цвет', value: 'Белый'}],
    isActive: true,
  },
  {
    id: '4',
    sku: 'ASKM-GYP-004',
    name: {
      en: 'Geometric Gypsum Planter',
      ru: 'Геометрический гипсовый кашпо',
      uz: 'Geometrik gipsli gul tuvak',
    },
    description: {
      en: 'Modern gypsum planter with a minimalist geometric design. Ideal for succulents.',
      ru: 'Современное гипсовое кашпо с минималистичным геометрическим дизайном. Идеально подходит для суккулентов.',
      uz: 'Minimalistik geometrik dizayndagi zamonaviy gipsli gul tuvak. Sukkulentlar uchun juda mos.',
    },
    price: 187500,
    costPrice: 120000,
    category: 'Гипсовый рай',
    images: ['https://placehold.co/600x400.png?text=Gypsum+Planter'],
    mainImage: 'https://placehold.co/600x400.png?text=Gypsum+Planter',
    material: 'Натуральный гипс',
    dimensions: '10см x 10см x 8см',
    burningTime: 'N/A',
    stock: 25,
    attributes: [{key: 'Отделка', value: 'Матово-белая'}],
    isActive: true,
  },
  {
    id: '5',
    sku: 'ASKM-ROS-005',
    name: {
      en: 'Rose Garden Candle',
      ru: 'Свеча "Розовый Сад"',
      uz: 'Atirgul Bog\'i Shami',
    },
    description: {
      en: 'Experience the fragrance of a blooming rose garden with this exquisite candle.',
      ru: 'Ощутите аромат цветущего розового сада с этой изысканной свечой.',
      uz: 'Ushbu nafis sham bilan gullab-yashnayotgan atirgul bog\'ining iforini his eting.',
    },
    price: 260000,
    costPrice: 175000,
    category: 'Аромасвечи',
    images: ['https://placehold.co/600x400.png?text=Rose+Candle'],
    mainImage: 'https://placehold.co/600x400.png?text=Rose+Candle',
    scent: 'Свежие розы',
    material: 'Соевый воск',
    dimensions: '8.5см x 11см',
    burningTime: 'Примерно 50 часов',
    stock: 12,
    attributes: [{key: 'Цвет', value: 'Розовый'}],
    isActive: false, 
  },
  {
    id: '6',
    sku: 'ASKM-COA-006',
    name: {
      en: 'Abstract Gypsum Coasters (Set of 4)',
      ru: 'Абстрактные гипсовые подставки (набор из 4 шт.)',
      uz: 'Abstrakt gipsli tagliklar (4 dona to\'plam)',
    },
    description: {
      en: 'Protect your surfaces with style using these unique abstract design gypsum coasters.',
      ru: 'Защитите свои поверхности стильно с помощью этих уникальных гипсовых подставок с абстрактным дизайном.',
      uz: 'Ushbu noyob abstrakt dizayndagi gipsli tagliklar yordamida sirtlaringizni zamonaviy tarzda himoya qiling.',
    },
    price: 299900,
    costPrice: 190000,
    category: 'Гипсовый рай',
    images: ['https://placehold.co/600x400.png?text=Gypsum+Coasters'],
    mainImage: 'https://placehold.co/600x400.png?text=Gypsum+Coasters',
    material: 'Усиленный гипс',
    dimensions: 'Диаметр 10см, толщина 1см (каждая)',
    burningTime: 'N/A',
    stock: 0,
    attributes: [{key: 'Узор', value: 'Абстрактный вихрь'}],
    isActive: true,
  },
  {
    id: '7',
    sku: 'ASKM-CORP-001',
    name: {
      en: 'Corporate Gift Set "Prestige"',
      ru: 'Корпоративный подарочный набор "Престиж"',
      uz: '"Prestige" korporativ sovg\'a to\'plami',
    },
    description: {
      en: 'A premium selection of scented candles and gypsum accessories, perfect for corporate gifting.',
      ru: 'Премиальный набор ароматических свечей и гипсовых аксессуаров, идеально подходящий для корпоративных подарков.',
      uz: 'Korporativ sovg\'alar uchun juda mos keladigan xushbo\'y shamlar va gips aksessuarlarining premium to\'plami.',
    },
    price: 750000,
    costPrice: 480000,
    category: 'Корпоративные наборы',
    images: ['https://placehold.co/600x400.png?text=Corporate+Set+Prestige'],
    mainImage: 'https://placehold.co/600x400.png?text=Corporate+Set+Prestige',
    scent: 'Assorted Premium Scents',
    material: 'Soy Wax, Gypsum',
    dimensions: 'Varies per item',
    burningTime: 'Varies',
    stock: 50,
    attributes: [{key: 'Packaging', value: 'Premium Gift Box'}],
    isActive: true,
  },
  {
    id: '8',
    sku: 'ASKM-WED-001',
    name: {
      en: 'Wedding Favor Scented Sachet',
      ru: 'Аромасаше "Свадебный комплимент"',
      uz: 'To\'y uchun xushbo\'y sashe',
    },
    description: {
      en: 'Elegant scented sachets, a lovely token of appreciation for your wedding guests.',
      ru: 'Элегантные аромасаше, прекрасный знак внимания для ваших свадебных гостей.',
      uz: 'Nafis xushbo\'y sashelar, to\'y mehmonlaringiz uchun ajoyib minnatdorchilik belgisi.',
    },
    price: 45000,
    costPrice: 25000, 
    category: 'Свадебные комплименты',
    images: ['https://placehold.co/600x400.png?text=Wedding+Sachet'],
    mainImage: 'https://placehold.co/600x400.png?text=Wedding+Sachet',
    scent: 'Jasmine & Lily',
    material: 'Fabric, Scented Beads',
    dimensions: '8cm x 12cm',
    burningTime: 'N/A',
    stock: 200,
    attributes: [{key: 'Custom Tag', value: 'Available upon request'}],
    isActive: true,
  },
   {
    id: '9',
    sku: 'ASKM-HOME-001',
    name: {
      en: 'Home Fragrance Diffuser "Citrus Grove"',
      ru: 'Аромадиффузор для дома "Цитрусовая Роща"',
      uz: '"Sitrus Bog\'i" uy uchun aromadiffuzor',
    },
    description: {
      en: 'Brighten your home with the uplifting scent of citrus fruits.',
      ru: 'Освежите свой дом бодрящим ароматом цитрусовых фруктов.',
      uz: 'Sitrus mevalarining tetiklantiruvchi ifori bilan uyingizni yoritib yuboring.',
    },
    price: 320000,
    costPrice: 200000,
    category: 'Вкусный дом',
    images: ['https://placehold.co/600x400.png?text=Citrus+Diffuser'],
    mainImage: 'https://placehold.co/600x400.png?text=Citrus+Diffuser',
    scent: 'Citrus Blend',
    material: 'Glass, Reed Sticks',
    dimensions: '200ml Bottle',
    burningTime: 'N/A (Diffuser)',
    stock: 30,
    attributes: [{key: 'Duration', value: 'Approx. 3 months'}],
    isActive: true,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'order123',
    orderNumber: 'ASKM-001',
    date: '2023-10-26',
    status: 'Delivered',
    totalAmount: (mockProducts.find(p=>p.id==='1')?.price || 0) + (mockProducts.find(p=>p.id==='4')?.price || 0),
    items: [
      { ...(mockProducts.find(p=>p.id==='1')!), quantity: 1, price: mockProducts.find(p=>p.id==='1')!.price },
      { ...(mockProducts.find(p=>p.id==='4')!), quantity: 1, price: mockProducts.find(p=>p.id==='4')!.price },
    ],
  },
  {
    id: 'order124',
    orderNumber: 'ASKM-002',
    date: '2023-11-05',
    status: 'Shipped',
    totalAmount: mockProducts.find(p=>p.id==='2')?.price || 0,
    items: [{ ...(mockProducts.find(p=>p.id==='2')!), quantity: 1, price: mockProducts.find(p=>p.id==='2')!.price }],
  },
  {
    id: 'order125',
    orderNumber: 'ASKM-003',
    date: '2023-11-10',
    status: 'Processing',
    totalAmount: (mockProducts.find(p=>p.id==='3')?.price || 0) + (mockProducts.find(p=>p.id==='5')?.price || 0), 
    items: [
      { ...(mockProducts.find(p=>p.id==='3')!), quantity: 1, price: mockProducts.find(p=>p.id==='3')!.price },
      ...(mockProducts.find(p=>p.id==='5') ? [{ ...(mockProducts.find(p=>p.id==='5')!), quantity: 1, price: mockProducts.find(p=>p.id==='5')!.price }] : [])
    ],
  },
];

export const mockAdminClients: MockAdminClient[] = [
  { id: 'client-001', name: 'Alisher Usmanov', email: 'alisher.u@example.com', registrationDate: '2023-01-15T10:00:00Z', totalOrders: 5, totalSpent: 125000000, isBlocked: false },
  { id: 'client-002', name: 'Gulnara Karimova', email: 'gulnara.k@example.com', registrationDate: '2023-03-22T14:30:00Z', totalOrders: 2, totalSpent: 45000000, isBlocked: false },
  { id: 'client-003', name: 'Timur Begaliev', email: 'timur.b@example.com', registrationDate: '2023-05-10T09:15:00Z', totalOrders: 8, totalSpent: 210000000, isBlocked: true },
  { id: 'client-004', name: 'Dildora Ahmedova', email: 'dildora.a@example.com', registrationDate: '2023-07-01T11:00:00Z', totalOrders: 1, totalSpent: 22990000, isBlocked: false },
  { id: 'client-005', name: 'Rustam Qosimov', email: 'rustam.q@example.com', registrationDate: '2023-08-19T18:45:00Z', totalOrders: 12, totalSpent: 350000000, isBlocked: false },
];
